spring:
  application:
    name: courier-tracking

  datasource:
    url: jdbc:postgresql://localhost:5432/courier_tracking
    username: postgres
    password: G7r#x9Lq2Tz8Pw!

  data:
    redis:
      host: localhost
      port: 6379

  jackson:
    time-zone: UTC

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.default_schema: couriertracking

  flyway:
    enabled: true
    schemas: couriertracking
    default-schema: couriertracking
    create-schemas: true

  messages:
    basename: messages

app:
  geo:
    radius-meters: 100
  dedup:
    entrance-ttl-seconds: 60
    client-window-seconds: 60
  locks:
    per-courier-ttl-seconds: 15
  last-location:
    ttl-seconds: 86400